name: Update Data and Deploy to GitHub Pages

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          
      - name: Run crypto data update
        run: |
          python scripts/download-historical-data.py
          
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "📊 Data changes detected"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "✅ No data changes"
          fi
          
      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/
          git commit -m "🤖 Update crypto data - $(date +'%Y-%m-%d %H:%M UTC')"
          git push
          
      - name: Setup Node.js
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Node dependencies
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: npm ci
        
      - name: Build project
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: npm run build
        
      - name: Setup Pages
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        if: steps.verify-changed-files.outputs.changed == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
          
      - name: Summary
        run: |
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "✅ Data updated and deployed to GitHub Pages successfully"
            echo "🌐 Site URL: ${{ steps.deployment.outputs.page_url }}"
          else
            echo "ℹ️ No changes detected, skipping deployment"
          fi
